import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { Button } from "~/components/ui/button";
import Link from "next/link";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <nav className="fixed top-0 left-0 w-full bg-transparent p-4 text-white flex gap-8">
          <Link href={'/'}>Home</Link>
          <Link href={'/server'}>Server Component</Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
